### ISSUE TITLE
Some large files were commited in the history of the repository

### ISSUE THREAD

**Issue by Bachibouzouk** [RAMP-project/RAMP#31]
The total size of the latest stand files is 4.3Mo. However, the size of the repository is 97.4 Mo

I ran the command ```git rev-list --objects --all | git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' | sed -n 's/^blob //p' | sort --numeric-sort --key=2 | cut -c 1-12,41- | $(command -v gnumfmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest```

And what comes out is 
```
1d40db6f2503  1,5MiB RAMP_v02-pre/results/DE - Validation/Charging Profiles.csv
f99cf00e37f2  1,7MiB RAMP_v02-pre/TimeSeries/temp.csv
19ad18ac29cb  1,9MiB RAMP_v02-pre/results/DE - Validation/Availability Factors.csv
1f46a1afeae2  1,9MiB RAMP_v02-pre/results/output_file_1_U1.csv
b8f200288a79  4,0MiB RAMP_v02-pre/time_series/ambient_temperatures.csv
2087c3d63b1b   11MiB RAMP_v02-pre/results/output_file_2.csv
d1c327524151   17MiB RAMP_v02-pre/Input_data/time_series_60min_singleindex_filtered.csv
9244289c6676   26MiB RAMP_v02-pre/results/output_file_3.csv
493fbb112733   61MiB RAMP_v02-pre/Input_data/ninja_pv_europe_v1.1_sarah.csv
abfd2ec6c587   63MiB RAMP_v02-pre/Input_data/temp_ninja_pop.csv
6e2b8f98ed29   63MiB RAMP_v02-pre/Input_data/ninja_pv_europe_v1.1_merra2.csv
db95a0200fcf   89MiB RAMP_v02-pre/Input_data/ninja_wind_europe_v1.1_current_national.csv
```

I am unsure to which extend rewriting the history by removing those commits is wished. In any case I wanted to point out the problem and propose a potential solution : https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

**Comment by FLomb** [comment]
Hi, thanks, yes - this just really shows how bad was our (or at least my) understanding of repositories and GitHub when we uploaded the first version of the code here. We ended up uploading many completely unnecessary files, just because we had them in the same folder (e.g., because we used some of them for some figures in the paper, or for some other applications). So it's totally on purpose that those files are not there anymore; they should never have.

Is your proposed solution something that would let us get rid of those from the history of the repo?

**Comment by Bachibouzouk** [comment]
I think the only problem with my proposed solution is that it rewrites the history, so someone connected locally with the old `master` branch should delete their local copy, then pull the newest master branch. I am not sure about this but this might also disrupt open PRs and forks (just adding a bit of work to people that need to do a rebase on the new branch). So if you have a 1000 download and 10 PRs a day it might not be good to do. But as I see the last updates on the branches are quite old (10 months). I did it on another repository of ours and it worked, so I can assist you if needed :)

**Comment by FLomb** [comment]
Ok, well, it might indeed be an opportune moment to do this because there's not a lot of activity right now (in terms of PRs, at least).

The information provided by your link is very clear, so I should be able to handle this by myself. However, it looks like a non-trivial process, which even involves contacting GitHub's support. Have you done that too for the other repository you mentioned, or have you just used the `git-filter-repo` without going as far as asking GitHub to remove cached views and references?

**Comment by Bachibouzouk** [comment]
I did not contacted GitHub (because I knew there were no forks or many people who could have clone the repo). To remove files from history I used
`git-filter-repo --invert-path --path <path to file>`

If it can help you, I also used a shell script to remove many similar files in a folder (you have to figure out which `ls` option you need to provide to get your files, or use glob:
 
 `for file in $(ls <path to file>); do git-filter-repo --invert-path --path <path to file>/$file;done`

**Comment by Bachibouzouk** [comment]
In this case I guess the main difficulty is to let the people with active forks know they should `rebase` and not `merge` after you cleant the repo, then they can `merge` again. There are not much active branch on this repo, and I have no problem to rebase RLI's fork onto a cleaned RAMP repo :)

**Comment by Bachibouzouk** [comment]
I would also take the opportunity to remove `.pyc` files, `__pycache__` folder and to add them to `.gitignore`. I would also remove the files in `results`as they are a duplicate of the files in `test`, then also add `results folder to `.gitignore` to avoid user pushing their results

**Comment by Bachibouzouk** [comment]
@FLomb and I noticed in a joint call that the files originated form an old branch which was removed and the repo now only weighs 10 Mo, another branch `EU_cooking_profiles` still have part of those files. @FLomb  will package this branch as standalone on Zenodo and then delete the branch on the repository, this solves the issue.

**Comment by FLomb** [comment]
The branch has been deleted and is now available as a standalone application on Zenodo: https://doi.org/10.5281/zenodo.7118534
