### ISSUE TITLE
Function download_example does not work

### ISSUE THREAD

**Issue by LorenzoRinaldi** [RAMP-project/RAMP#66]
I was trying to use the "download_example" function (ramp\example\examples.py) and it seems there is an issue with the "shower_p.csv" file, which i guess it is supposed to be present in the folder "site-packages\ramp\example" but it is not. Temporarily fixed by removing that filw from the list of files in the "download_example" function

**Comment by Bachibouzouk** [comment]
This is a mistake, they should be included, you can find them and download them from https://github.com/RAMP-project/RAMP/tree/main/ramp/example

**Comment by FLomb** [comment]
Thanks for testing the new version @LorenzoRinaldi; we were expecting a few minor bugs like this one to have gone unnoticed and to pop up as soon as more people tried using the code for their own typical applications. That's very helpful. We'll fix this asap.

**Comment by mohammadamint** [comment]
the issue seems to be in the setup.py where csv files are missing in the package_data, and they are not uploaded along with the package in pypi dist.

package_data={"": ["*.txt", "*.dat", "*.doc", "*.rst","*.xlsx"]}

**Comment by FLomb** [comment]
This has been fixed by PR #69 on the `development` branch. We are now pushing the same fix to the `main` branch with PR #70, after which we'll close the issue. To use the fixed version of the code, you'll need to download it from the main (or development) branch and install it locally, following the [installation method from the source code](https://rampdemand.readthedocs.io/en/latest/intro.html#installing-through-source-code).

We also plan to release a new pip version (v0.4.1) with this and other minor fixes in a few days, as soon as people will have had enough time to play with v0.4.0 and detect any issues. When that happens, you'll be able to just install the software via pip again with the fix implemented.
